[project]
name = "satellite-to-ground-no2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "prajin gn", email = "prajin376@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "notebook>=7.6.3",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]

[project.scripts]
satellite-to-ground-no2 = "satellite_to_ground_no2:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
